name: truefaux
favicon: null
layout_spectrum: 0.49504
typography_spectrum: 0.394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090b0a'
    - '#d7dde9'
    - '#334645'
    - '#7595a1'
    - '#a1b7c5'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
