typography_spectrum: 0.394
color:
  brandColors:
    - '#090b0a'
    - '#d7dde9'
    - '#334645'
    - '#7595a1'
    - '#a1b7c5'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49504
analytics:
  google: null
  facebook: null
  twitter: null
name: truefaux
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: TRUEFAUX
purpose: []
